import type { DashboardStats } from "./dashboard-api";

const demoUpdatedAt = "2026-06-18T09:20:00.000Z";

export const demoDashboardStats: DashboardStats = {
  totalTickets: 38,
  openTickets: 12,
  inProgressTickets: 14,
  resolvedTickets: 9,
  closedTickets: 3,
  urgentTickets: 7,
  createdToday: 6,
  statusDistribution: [
    { key: "answer_pending", label: "답변 대기", count: 26, percentage: 68 },
    { key: "resolved", label: "답변 완료", count: 9, percentage: 24 },
    { key: "closed", label: "종료", count: 3, percentage: 8 },
  ],
  categoryDistribution: [
    { key: "account", label: "계정", count: 8, percentage: 21 },
    { key: "billing", label: "결제", count: 10, percentage: 26 },
    { key: "technical", label: "기술 지원", count: 12, percentage: 32 },
    { key: "product", label: "제품 문의", count: 6, percentage: 16 },
    { key: "other", label: "기타", count: 2, percentage: 5 },
  ],
  recentTickets: [
    {
      id: "demo-ticket-1042",
      title: "기업 플랜 결제 영수증 재발급 요청",
      ticket_number: 1042,
      customer: { email: "ops@acme.example", name: "Acme Korea" },
      assignee: { email: "jiwon@example.com", name: "이지원" },
      category: "billing",
      priority: "high",
      status: "in_progress",
      ai_needs_review: true,
      ai_sentiment: "negative",
      ai_urgency: "high",
      ai_confidence: 0.68,
      created_at: "2026-06-18T08:45:00.000Z",
      updated_at: demoUpdatedAt,
    },
    {
      id: "demo-ticket-1041",
      title: "SSO 로그인 후 워크스페이스가 보이지 않음",
      ticket_number: 1041,
      customer: { email: "it@northstar.example", name: "Northstar Labs" },
      assignee: { email: "minsu@example.com", name: "박민수" },
      category: "technical",
      priority: "urgent",
      status: "open",
      ai_needs_review: true,
      ai_sentiment: "negative",
      ai_urgency: "critical",
      ai_confidence: 0.62,
      created_at: "2026-06-18T08:20:00.000Z",
      updated_at: "2026-06-18T09:05:00.000Z",
    },
    {
      id: "demo-ticket-1038",
      title: "월간 사용량 리포트 기준 확인 요청",
      ticket_number: 1038,
      customer: { email: "admin@bluefin.example", name: "Bluefin" },
      assignee: { email: "seoyeon@example.com", name: "최서연" },
      category: "product",
      priority: "medium",
      status: "in_progress",
      ai_needs_review: false,
      ai_sentiment: "neutral",
      ai_urgency: "low",
      ai_confidence: 0.91,
      created_at: "2026-06-17T11:10:00.000Z",
      updated_at: "2026-06-18T08:30:00.000Z",
    },
    {
      id: "demo-ticket-1037",
      title: "제품 사용량 리포트 다운로드 오류",
      ticket_number: 1037,
      customer: { email: "support@motion.example", name: "Motion Grid" },
      assignee: null,
      category: "product",
      priority: "high",
      status: "open",
      ai_needs_review: false,
      ai_sentiment: "neutral",
      ai_urgency: "medium",
      ai_confidence: 0.84,
      created_at: "2026-06-17T10:30:00.000Z",
      updated_at: "2026-06-18T07:20:00.000Z",
    },
  ],
};
