import type { DashboardStats } from "./dashboard-api";

const demoUpdatedAt = "2026-06-18T09:20:00.000Z";

export const demoDashboardStats: DashboardStats = {
  totalTickets: 38,
  openTickets: 12,
  inProgressTickets: 14,
  resolvedTickets: 9,
  closedTickets: 3,
  urgentTickets: 7,
  createdToday: 6,
  activeTickets: 26,
  highUrgencyTickets: 8,
  negativeSentimentTickets: 5,
  reviewRequiredTickets: 9,
  unassignedActiveTickets: 4,
  statusDistribution: [
    { key: "answer_pending", label: "답변 대기", count: 26, percentage: 68 },
    { key: "resolved", label: "답변 완료", count: 9, percentage: 24 },
    { key: "closed", label: "종료", count: 3, percentage: 8 },
  ],
  categoryDistribution: [
    { key: "account", label: "계정", count: 8, percentage: 21 },
    { key: "billing", label: "결제", count: 10, percentage: 26 },
    { key: "technical", label: "기술 지원", count: 12, percentage: 32 },
    { key: "product", label: "제품 문의", count: 6, percentage: 16 },
    { key: "other", label: "기타", count: 2, percentage: 5 },
  ],
  assigneeWorkload: [
    {
      key: "unassigned",
      assigneeId: null,
      label: "담당자 필요",
      email: null,
      answerPendingCount: 1,
      urgentCount: 0,
      needsReviewCount: 0,
    },
    {
      key: "agent-jiwon",
      assigneeId: "agent-jiwon",
      label: "이지원",
      email: "jiwon@example.com",
      answerPendingCount: 1,
      urgentCount: 0,
      needsReviewCount: 1,
    },
    {
      key: "agent-minsu",
      assigneeId: "agent-minsu",
      label: "박민수",
      email: "minsu@example.com",
      answerPendingCount: 1,
      urgentCount: 1,
      needsReviewCount: 1,
    },
    {
      key: "agent-seoyeon",
      assigneeId: "agent-seoyeon",
      label: "최서연",
      email: "seoyeon@example.com",
      answerPendingCount: 1,
      urgentCount: 0,
      needsReviewCount: 0,
    },
  ],
  recentTickets: [
    {
      id: "demo-ticket-1042",
      title: "기업 플랜 결제 영수증 재발급 요청",
      ticket_number: 1042,
      customer: {
        id: "customer-acme",
        email: "ops@acme.example",
        name: "Acme Korea",
      },
      assignee: {
        id: "agent-jiwon",
        email: "jiwon@example.com",
        name: "이지원",
      },
      category: "billing",
      priority: "high",
      status: "in_progress",
      ai_needs_review: true,
      ai_sentiment: "negative",
      ai_urgency: "high",
      ai_confidence: 0.68,
      created_at: "2026-06-18T08:45:00.000Z",
      updated_at: demoUpdatedAt,
    },
    {
      id: "demo-ticket-1041",
      title: "SSO 로그인 후 워크스페이스가 보이지 않음",
      ticket_number: 1041,
      customer: {
        id: "customer-northstar",
        email: "it@northstar.example",
        name: "Northstar Labs",
      },
      assignee: {
        id: "agent-minsu",
        email: "minsu@example.com",
        name: "박민수",
      },
      category: "technical",
      priority: "urgent",
      status: "open",
      ai_needs_review: true,
      ai_sentiment: "negative",
      ai_urgency: "critical",
      ai_confidence: 0.62,
      created_at: "2026-06-18T08:20:00.000Z",
      updated_at: "2026-06-18T09:05:00.000Z",
    },
    {
      id: "demo-ticket-1038",
      title: "월간 사용량 리포트 기준 확인 요청",
      ticket_number: 1038,
      customer: {
        id: "customer-bluefin",
        email: "admin@bluefin.example",
        name: "Bluefin",
      },
      assignee: {
        id: "agent-seoyeon",
        email: "seoyeon@example.com",
        name: "최서연",
      },
      category: "product",
      priority: "medium",
      status: "in_progress",
      ai_needs_review: false,
      ai_sentiment: "neutral",
      ai_urgency: "low",
      ai_confidence: 0.91,
      created_at: "2026-06-17T11:10:00.000Z",
      updated_at: "2026-06-18T08:30:00.000Z",
    },
    {
      id: "demo-ticket-1037",
      title: "제품 사용량 리포트 다운로드 오류",
      ticket_number: 1037,
      customer: {
        id: "customer-motion",
        email: "support@motion.example",
        name: "Motion Grid",
      },
      assignee: null,
      category: "product",
      priority: "high",
      status: "open",
      ai_needs_review: false,
      ai_sentiment: "neutral",
      ai_urgency: "medium",
      ai_confidence: 0.84,
      created_at: "2026-06-17T10:30:00.000Z",
      updated_at: "2026-06-18T07:20:00.000Z",
    },
  ],
};
