-- SupportFlow initial Supabase schema.
-- Run this in the Supabase SQL editor before connecting real auth flows.

create extension if not exists "pgcrypto";

create type public.user_role as enum ('customer', 'agent', 'admin');
create type public.ticket_status as enum (
  'open',
  'in_progress',
  'resolved',
  'closed'
);
create type public.ticket_priority as enum (
  'low',
  'medium',
  'high',
  'urgent'
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  role public.user_role not null default 'customer',
  created_at timestamptz not null default now()
);

create table public.tickets (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content text not null,
  status public.ticket_status not null default 'open',
  priority public.ticket_priority not null default 'medium',
  category text not null,
  ticket_number bigint generated by default as identity unique,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  assignee_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ticket_replies (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  is_internal boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.ticket_logs (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  action text not null,
  before_value text,
  after_value text,
  created_at timestamptz not null default now()
);

create index tickets_customer_id_idx on public.tickets(customer_id);
create index tickets_assignee_id_idx on public.tickets(assignee_id);
create index tickets_status_idx on public.tickets(status);
create index tickets_priority_idx on public.tickets(priority);
create index tickets_created_at_idx on public.tickets(created_at desc);
create index ticket_replies_ticket_id_idx on public.ticket_replies(ticket_id);
create index ticket_logs_ticket_id_idx on public.ticket_logs(ticket_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger tickets_set_updated_at
before update on public.tickets
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    coalesce((new.raw_user_meta_data ->> 'role')::public.user_role, 'customer')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select role
  from public.profiles
  where id = auth.uid()
$$;

create or replace function public.can_view_profile(target_profile_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select
    auth.uid() = target_profile_id
    or exists (
      select 1
      from public.profiles
      where id = auth.uid()
      and role = 'admin'
    )
    or (
      exists (
        select 1
        from public.profiles
        where id = auth.uid()
        and role = 'agent'
      )
      and exists (
        select 1
        from public.tickets
        where customer_id = target_profile_id
        and assignee_id = auth.uid()
      )
    )
    or exists (
      select 1
      from public.tickets
      where customer_id = auth.uid()
      and assignee_id = target_profile_id
    )
$$;

create or replace function public.create_ticket_reply(
  p_ticket_id uuid,
  p_content text,
  p_is_internal boolean default false
)
returns public.ticket_replies
language plpgsql
security definer
set search_path = public
as $$
declare
  current_role public.user_role;
  created_reply public.ticket_replies;
begin
  select role
  into current_role
  from public.profiles
  where id = auth.uid();

  if auth.uid() is null or current_role is null then
    raise exception '로그인이 필요합니다.';
  end if;

  if current_role = 'customer' then
    raise exception 'Customers cannot create support replies.';
  end if;

  if current_role = 'agent' and not exists (
    select 1
    from public.tickets
    where id = p_ticket_id
    and assignee_id = auth.uid()
  ) then
    raise exception 'Ticket not found or access denied.';
  end if;

  if current_role = 'admin' and not exists (
    select 1
    from public.tickets
    where id = p_ticket_id
  ) then
    raise exception 'Ticket not found or access denied.';
  end if;

  if p_is_internal = false and exists (
    select 1
    from public.ticket_replies
    where ticket_id = p_ticket_id
    and is_internal = false
  ) then
    raise exception '이미 고객 답변이 등록된 문의입니다.';
  end if;

  insert into public.ticket_replies (
    ticket_id,
    author_id,
    content,
    is_internal
  )
  values (
    p_ticket_id,
    auth.uid(),
    p_content,
    p_is_internal
  )
  returning *
  into created_reply;

  if p_is_internal = false then
    update public.tickets
    set status = 'resolved'
    where id = p_ticket_id
    and status in ('open', 'in_progress');
  end if;

  insert into public.ticket_logs (
    ticket_id,
    actor_id,
    action,
    before_value,
    after_value
  )
  values (
    p_ticket_id,
    auth.uid(),
    case when p_is_internal then 'internal_note_added' else 'reply_added' end,
    null,
    created_reply.id::text
  );

  return created_reply;
end;
$$;

grant execute on function public.create_ticket_reply(uuid, text, boolean)
to authenticated;

alter table public.profiles enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_replies enable row level security;
alter table public.ticket_logs enable row level security;

create policy "Profiles are visible by support context"
on public.profiles
for select
to authenticated
using (public.can_view_profile(id));

create policy "Profiles can be updated by the owner"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Customers can create their own tickets"
on public.tickets
for insert
to authenticated
with check (auth.uid() = customer_id);

create policy "Customers can view their own tickets"
on public.tickets
for select
to authenticated
using (auth.uid() = customer_id);

create policy "Agents can view assigned tickets"
on public.tickets
for select
to authenticated
using (
  auth.uid() = assignee_id
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'agent'
  )
);

create policy "Admins can view all tickets"
on public.tickets
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);

create policy "Agents can update assigned tickets"
on public.tickets
for update
to authenticated
using (
  auth.uid() = assignee_id
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'agent'
  )
)
with check (
  auth.uid() = assignee_id
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'agent'
  )
);

create policy "Admins can update all tickets"
on public.tickets
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);

create policy "Customers can view public replies on own tickets"
on public.ticket_replies
for select
to authenticated
using (
  is_internal = false
  and exists (
    select 1
    from public.tickets
    where tickets.id = ticket_replies.ticket_id
    and tickets.customer_id = auth.uid()
  )
);

create policy "Agents can view replies on assigned tickets"
on public.ticket_replies
for select
to authenticated
using (
  exists (
    select 1
    from public.tickets
    join public.profiles on profiles.id = auth.uid()
    where tickets.id = ticket_replies.ticket_id
    and tickets.assignee_id = auth.uid()
    and profiles.role = 'agent'
  )
);

create policy "Admins can view all replies"
on public.ticket_replies
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);

create policy "Agents can create replies on assigned tickets"
on public.ticket_replies
for insert
to authenticated
with check (
  author_id = auth.uid()
  and exists (
    select 1
    from public.tickets
    join public.profiles on profiles.id = auth.uid()
    where tickets.id = ticket_replies.ticket_id
    and tickets.assignee_id = auth.uid()
    and profiles.role = 'agent'
  )
);

create policy "Admins can create all ticket replies"
on public.ticket_replies
for insert
to authenticated
with check (
  author_id = auth.uid()
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);

create policy "Agents can view logs on assigned tickets"
on public.ticket_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.tickets
    join public.profiles on profiles.id = auth.uid()
    where tickets.id = ticket_logs.ticket_id
    and tickets.assignee_id = auth.uid()
    and profiles.role = 'agent'
  )
);

create policy "Admins can view all ticket logs"
on public.ticket_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);

create policy "Agents can create logs on assigned tickets"
on public.ticket_logs
for insert
to authenticated
with check (
  actor_id = auth.uid()
  and exists (
    select 1
    from public.tickets
    join public.profiles on profiles.id = auth.uid()
    where tickets.id = ticket_logs.ticket_id
    and tickets.assignee_id = auth.uid()
    and profiles.role = 'agent'
  )
);

create policy "Admins can create ticket logs"
on public.ticket_logs
for insert
to authenticated
with check (
  actor_id = auth.uid()
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);
